{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "event-forwarder-gelf.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "event-forwarder-gelf.name" . }}
    helm.sh/chart: {{ include "event-forwarder-gelf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
{{- end }}
