{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "event-forwarder-gelf.serviceAccountName" . }}
  labels:
  labels:
    app.kubernetes.io/name: {{ include "event-forwarder-gelf.name" . }}
    helm.sh/chart: {{ include "event-forwarder-gelf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
