name: hpa-operator
version: 0.0.6
description: A Helm chart for Kubernetes
home: https://banzaicloud.com
sources:
  - https://github.com/banzaicloud/hpa-operator
keywords:
- hpa
- autoscale
maintainers:
- name: komljen
  email: alen.komljen@live.com
  url: https://akomljen.com
