apiVersion: v1
appVersion: "v0.8.0"
description: A Helm chart for Kubernetes Descheduler
name: descheduler
version: 0.2.1
keywords:
- descheduler
home: https://github.com/kubernetes-incubator/descheduler
maintainers:
- name: komljen
  email: alen.komljen@live.com
