apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "descheduler.fullname" . }}
  labels:
    app: {{ template "descheduler.name" . }}
    chart: {{ template "descheduler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  deschedulerpolicy.yaml: |-
    apiVersion: descheduler/v1alpha1
    kind: DeschedulerPolicy
{{ toYaml .Values.deschedulerPolicy | indent 4 }}
