apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "descheduler.fullname" . }}
  labels:
    app: {{ template "descheduler.name" . }}
    chart: {{ template "descheduler.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app: {{ template "descheduler.name" . }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: "true"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      template:
        spec:
          serviceAccountName: {{ template "descheduler.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - mountPath: /policy-dir
              name: policy-volume
            command:
            - /bin/descheduler
            - --policy-config-file=/policy-dir/deschedulerpolicy.yaml
            {{- range $key, $value := .Values.cmdOptions }}
            - --{{ $key }}{{ if $value }}={{ $value }}{{ end }}
            {{- end }}
          restartPolicy: "OnFailure"
          volumes:
          - name: policy-volume
            configMap:
              name: {{ template "descheduler.fullname" . }}
