apiVersion: v1
kind: Service
metadata:
  name: {{ include "contour.fullname" . }}
  labels:
    app: {{ template "contour.name" . }}
    chart: {{ template "contour.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.proxy.service.annotations | indent 4 }}
spec:
 ports:
 - port: 80
   name: http
   protocol: TCP
   targetPort: 8080
 - port: 443
   name: https
   protocol: TCP
   targetPort: 8443
 selector:
   app: {{ template "contour.name" . }}
   release: {{ .Release.Name }}
 type: {{ .Values.proxy.service.type }}
