## AWS region in which this ingress controller will operate
## REQUIRED
#
awsRegion: us-west-1

## Auto Discover awsRegion from ec2metadata, set this to true and omit awsRegion when ec2metadata is available.
autoDiscoverAwsRegion: false

## VPC ID of k8s cluster, required if ec2metadata is unavailable from controller pod
## Required if autoDiscoverAwsVpcID != true
awsVpcID: "vpc-xxx"

## Auto Discover awsVpcID from ec2metadata, set this to true and omit awsVpcID: " when ec2metadata is available.
autoDiscoverAwsVpcID: false

## Resources created by the ALB Ingress controller will be prefixed with this string
## REQUIRED
#
clusterName: k8s

image:
  repository: docker.io/amazon/aws-alb-ingress-controller
  tag: "v1.0.1"
  pullPolicy: IfNotPresent

extraArgs: {}

extraEnv: {}
  # AWS_ACCESS_KEY_ID: ""
  # AWS_SECRET_ACCESS_KEY: ""

nodeSelector: {}
  # node-role.kubernetes.io/node: "true"
  # tier: cs

tolerations: []
  #  - key: "node-role.kubernetes.io/master"
  #    effect: NoSchedule

podAnnotations: {}
  # iam.amazonaws.com/role: alb-ingress-controller

podLabels: {}

# How often (in seconds) to check controller readiness
readinessProbeInterval: 10

# How long to wait before the timeout (in seconds) when checking controller readiness
readinessProbeTimeout: 1

# How long to wait (in seconds) before checking the readiness probe
readinessProbeInitialDelay : 30

# How long to wait (in seconds) before checking the liveness probe
livenessProbeInitialDelay : 30

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 100Mi
  # requests:
  #   cpu: 100m
  #   memory: 100Mi

rbac:
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

scope:
  ## If provided, the ALB ingress controller will only act on Ingress resources annotated with this class
  ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-ingress-class
  #
  ingressClass: alb

  ## If true, the ALB ingress controller will only act on Ingress resources in a single namespace
  ## Default: false; watch all namespaces
  #
  singleNamespace: false

  ## If scope.singleNamespace=true, the ALB ingress controller will only act on Ingress resources in this namespace
  ## Ref: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/configuration.md#limiting-namespaces
  ## Default: namespace of the ALB ingress controller
  #
  watchNamespace: ""
